# Generated by Django 3.2.9 on 2021-11-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=45, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateField(null=True, verbose_name='Дата регистрации'),
        ),
    ]
