# Generated by Django 3.2.9 on 2021-11-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_rename_genre_name_genre_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
