# Generated by Django 3.2.9 on 2021-11-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211114_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre_name',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_name',
            new_name='name',
        ),
    ]
