# Generated by Django 3.2.9 on 2021-11-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(null=True, verbose_name='Рейтинг фильма'),
        ),
    ]
